version: '{build}'
image: Visual Studio 2019
configuration: Release
#platform: Any CPU
environment:
  TIMESTAMP: n/a
artifacts:
  - path: MATLab.zip
    name: MATLab
before_build:
- cmd: |-
    set TIMESTAMP=%date% %time%
    dotnet restore
build_script:
- cmd: dotnet publish MATLab -o pub
after_build:
- cmd: |-
    7z a MATLab.zip .\pub\*
    appveyor PushArtifact MATLab.zip
deploy:
- provider: GitHub
  tag: v3.0
  release: paracobNET
  description: |-
    This build is updated every commit (if possible).
    Always recommended to use latest versions.
    Datetime: $(TIMESTAMP)
    Message: "$(APPVEYOR_REPO_COMMIT_MESSAGE)"
  auth_token:
    secure: HzJBzil1ZFH9SbYQowaI8czAc0tVGO//+TX3qZz7TwTg9pLCQXKEnCe5HWojNeZ7
  repository: BenHall-7/paracobNET
  artifact: ParamXML.zip, ParamXML-exe.zip, prcScript.zip, prcScript-exe.zip, prcEditor.zip
  force_update: true
  on:
    branch: master